### ISSUE TITLE
it seems not compability with advanced roadmap v2

### ISSUE THREAD

**Issue by archonwang** [nanego/redmine_multiprojects_issue#15]
it seems not compability with advanced roadmap v2. any solution?
Thanks.

**Comment by archonwang** [comment]
the error log is 

> ActionView::Template::Error (Missing partial hooks/_stylesheet with {:locale=>[:zh, :en], :formats=>[:html], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :rsb]}. Searched in:
>   * "/opt/redmine-3.2/plugins/redmine_multiprojects_issue/app/views"
>   * "/opt/redmine-3.2/app/views"
> ):
>     13: <%= stylesheet_link_tag 'rtl', :media => 'all' if l(:direction) == 'rtl' %>
>     14: <%= javascript_heads %>
>     15: <%= heads_for_theme %>
>     16: <%= call_hook :view_layouts_base_html_head %>
>     17: 
>     18: <%= yield :header_tags -%>
>     19: </head>
>   lib/redmine/hook/view_listener.rb:59:in `block (2 levels) in render_on'
>   lib/redmine/hook/view_listener.rb:57:in `map'
>   lib/redmine/hook/view_listener.rb:57:in `block in render_on'
>   lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
>   lib/redmine/hook.rb:61:in `each'
>   lib/redmine/hook.rb:61:in `block in call_hook'
>   lib/redmine/hook.rb:58:in `tap'
>   lib/redmine/hook.rb:58:in `call_hook'
>   lib/redmine/hook.rb:96:in `call_hook'
>   app/views/layouts/base.html.erb:16:in `_3d73a1bd455b23796d2673bf7ec6ad91'
>   app/controllers/application_controller.rb:470:in `block (2 levels) in render_error'
>   app/controllers/application_controller.rb:468:in `render_error'
>   app/controllers/application_controller.rb:456:in `render_404'
>   app/controllers/application_controller.rb:480:in `missing_template'

**Comment by archonwang** [comment]
https://github.com/Coren/redmine_advanced_roadmap_v2/issues/74
