### ISSUE TITLE
Calendar 500 error with redmine 3.4.3

### ISSUE THREAD

**Issue by aozhi2nd** [nanego/redmine_multiprojects_issue#41]
```
Started GET "/projects/abq" for 10.1.10.22 at 2018-02-07 11:31:39 +0800
Processing by ProjectsController#show as HTML
  Parameters: {"id"=>"abq"}
  Current user: lgh (id=20)
  Rendered projects/_members_box.html.erb (22.0ms)
  Rendered news/_news.html.erb (7.1ms)
  Rendered plugins/advanced_roadmap/app/views/hooks/_milestones.html.erb (2.0ms)
  Rendered projects/show.html.erb within layouts/base (49.8ms)
  Rendered plugins/a_common_libs/app/views/hooks/a_common_libs/_html_head.html.erb (2.1ms)
  Rendered plugins/advanced_roadmap/app/views/hooks/_stylesheet.html.erb (0.3ms)
  Rendered plugins/redmine__select2/app/views/redmine__select2/_includes.html.erb (0.8ms)
  Rendered plugins/redmine_favourite_projects/app/views/favourite_projects/_favourite_projects_searchbox_partial.html.erb (0.2ms)
  Rendered plugins/redmine_banner/app/views/banner/_project_body_bottom.html.erb (2.3ms)
  Rendered plugins/sidebar_hide/app/views/sidebar/_hideButton_partial.html.erb (0.2ms)
Completed 200 OK in 440ms (Views: 99.9ms | ActiveRecord: 135.8ms)
Started GET "/issue_badge" for 10.1.10.22 at 2018-02-07 11:31:39 +0800
Processing by IssueBadgeController#index as */*
  Current user: lgh (id=20)
  Rendered plugins/redmine_issue_badge/app/views/issue_badge/_issue_badge.html.erb (0.5ms)
Completed 200 OK in 43ms (Views: 1.3ms | ActiveRecord: 8.4ms)
Started GET "/projects/abq/issues/gantt" for 10.1.10.22 at 2018-02-07 11:31:43 +0800
Processing by GanttsController#show as HTML
  Parameters: {"project_id"=>"abq"}
  Current user: lgh (id=20)
  Rendered queries/_filters.html.erb (25.9ms)
  Rendered plugins/advanced_roadmap/app/views/hooks/_milestones.html.erb (2.0ms)
  Rendered plugins/redmine_issue_templates/app/views/issue_templates/_issue_template_link.html.erb (1.3ms)
  Rendered issues/_sidebar.html.erb (10.4ms)
  Rendered gantts/show.html.erb within layouts/base (227.4ms)
  Rendered plugins/a_common_libs/app/views/hooks/a_common_libs/_html_head.html.erb (1.9ms)
  Rendered plugins/advanced_roadmap/app/views/hooks/_stylesheet.html.erb (0.4ms)
  Rendered plugins/redmine__select2/app/views/redmine__select2/_includes.html.erb (0.8ms)
  Rendered plugins/redmine_favourite_projects/app/views/favourite_projects/_favourite_projects_searchbox_partial.html.erb (0.2ms)
  Rendered plugins/redmine_banner/app/views/banner/_project_body_bottom.html.erb (2.3ms)
  Rendered plugins/sidebar_hide/app/views/sidebar/_hideButton_partial.html.erb (0.2ms)
Completed 200 OK in 418ms (Views: 249.8ms | ActiveRecord: 137.7ms)
Started GET "/issue_badge" for 10.1.10.22 at 2018-02-07 11:31:43 +0800
Processing by IssueBadgeController#index as */*
  Current user: lgh (id=20)
  Rendered plugins/redmine_issue_badge/app/views/issue_badge/_issue_badge.html.erb (1.0ms)
Completed 200 OK in 59ms (Views: 2.8ms | ActiveRecord: 9.6ms)
Started GET "/projects/kdcs/issues/calendar" for 10.1.10.22 at 2018-02-07 11:31:58 +0800
Processing by CalendarsController#show as HTML
  Parameters: {"project_id"=>"kdcs"}
  Current user: lgh (id=20)
  Rendered queries/_filters.html.erb (30.3ms)
  Rendered common/_calendar.html.erb (27.8ms)
  Rendered plugins/advanced_roadmap/app/views/hooks/_milestones.html.erb (3.4ms)
  Rendered plugins/redmine_issue_templates/app/views/issue_templates/_issue_template_link.html.erb (0.2ms)
  Rendered issues/_sidebar.html.erb (11.0ms)
  Rendered calendars/show.html.erb within layouts/base (74.9ms)
  Rendered plugins/a_common_libs/app/views/hooks/a_common_libs/_html_head.html.erb (1.9ms)
  Rendered plugins/advanced_roadmap/app/views/hooks/_stylesheet.html.erb (0.3ms)
  Rendered plugins/redmine__select2/app/views/redmine__select2/_includes.html.erb (0.8ms)
  Rendered plugins/redmine_favourite_projects/app/views/favourite_projects/_favourite_projects_searchbox_partial.html.erb (0.2ms)
  Rendered plugins/redmine_banner/app/views/banner/_project_body_bottom.html.erb (2.1ms)
  Rendered plugins/sidebar_hide/app/views/sidebar/_hideButton_partial.html.erb (0.2ms)
Completed 500 Internal Server Error in 317ms (Views: 119.7ms | ActiveRecord: 124.5ms)

ActiveRecord::StatementInvalid (Mysql2::Error: Unknown column 'issues.id' in 'IN/ALL/ANY subquery': SELECT `milestones`.`id` AS t0_r0, `milestones`.`name` AS t0_r1, `milestones`.`description` AS t0_r2, `milestones`.`milestone_effective_date` AS t0_r3, `milestones`.`user_id` AS t0_r4, `milestones`.`project_id` AS t0_r5, `milestones`.`created_on` AS t0_r6, `milestones`.`updated_on` AS t0_r7, `projects`.`id` AS t1_r0, `projects`.`name` AS t1_r1, `projects`.`description` AS t1_r2, `projects`.`homepage` AS t1_r3, `projects`.`is_public` AS t1_r4, `projects`.`parent_id` AS t1_r5, `projects`.`created_on` AS t1_r6, `projects`.`updated_on` AS t1_r7, `projects`.`identifier` AS t1_r8, `projects`.`status` AS t1_r9, `projects`.`lft` AS t1_r10, `projects`.`rgt` AS t1_r11, `projects`.`inherit_members` AS t1_r12, `projects`.`dmsf_description` AS t1_r13, `projects`.`dmsf_notification` AS t1_r14, `projects`.`default_assignee_id` AS t1_r15, `projects`.`text_formatting` AS t1_r16, `projects`.`modules_for_formatting` AS t1_r17, `projects`.`default_version_id` AS t1_r18, `projects`.`default_assigned_to_id` AS t1_r19, `projects`.`dmsf_act_as_attachable` AS t1_r20 FROM `milestones` INNER JOIN `projects` ON `projects`.`id` = `milestones`.`project_id` WHERE ((((projects.id = 90) OR issues.id IN (SELECT issue_id FROM issues_projects WHERE project_id = 90)))) AND (`milestones`.`milestone_effective_date` BETWEEN '2018-01-28' AND '2018-03-03')):
  plugins/advanced_roadmap/lib/advanced_roadmap/calendars_controller_patch.rb:27:in `add_milestones'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

```

Environment:
  Redmine version                3.4.3.stable
  Ruby version                   2.3.5-p376 (2017-09-14) [x86_64-linux]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.9.7
  Git                            1.7.1
  Filesystem                     
Redmine plugins:
  a_common_libs                  2.4.0
  advanced_roadmap               0.11.0
  gantt_extension                0.2
  projects_tree_view             0.0.9
  redmine__select2               1.1.0
  redmine_banner                 0.1.2
  redmine_base_deface            0.0.1
  redmine_base_stimulusjs        0.9.0
  redmine_category_tree          0.0.7
  redmine_checklists             3.1.10
  redmine_ckeditor               1.1.5
  redmine_dmsf                   1.6.0
  redmine_favourite_projects     0.9.1
  redmine_image_clipboard_paste  3.3.0
  redmine_issue_badge            0.0.6
  redmine_issue_templates        0.1.8
  redmine_lightbox2              0.4.3
  redmine_my_page                0.1.13
  redmine_per_project_formatting 0.0.4
  redmine_pivot_table            0.0.5
  redmine_questions              0.0.7
  redmine_work_time              0.3.4
  redmine_xlsx_format_issue_exporter 0.1.5
  sidebar_hide                   0.0.8
```

**Comment by nanego** [comment]
You did not provide enough information to fix this problem.
Your issue could come from any of the many plugins you are using. You could try to remove the "advanced_roadmap" plugin and see if it works without it.
