### ISSUE TITLE
An internal error is displayed in the browser when I want to look at Project -> Issues

### ISSUE THREAD

**Issue by n0rvik** [nanego/redmine_multiprojects_issue#48]
An internal error is displayed in the browser when I want to look at Project -> Issues

```
Internal error
An error occurred on the page you were trying to access.
If you continue to experience problems please contact your Redmine administrator for assistance.

If you are the Redmine administrator, check your log files for details about the error.
```
***

Install plugin:

``` 
~/redmine]$ bundle exec rake redmine:plugins  RAILS_ENV=production                         == 1 CreateIssuesProjects: migrating ==========================================
-- create_table(:issues_projects, {:id=>false})
   -> 0.0034s
== 1 CreateIssuesProjects: migrated (0.0036s) =================================

== 2 AddUniqueIndex: migrating ================================================
-- add_index(:issues_projects, [:issue_id, :project_id], {:unique=>true})
   -> 0.0056s
== 2 AddUniqueIndex: migrated (0.0057s) =======================================

== 3 AddAllowAnswersOnSecondaryProjectsToIssues: migrating ====================
-- add_column(:issues, :answers_on_secondary_projects, :boolean, {:default=>true, :null=>false})
   -> 0.0026s
== 3 AddAllowAnswersOnSecondaryProjectsToIssues: migrated (0.0028s) ===========
```
***

Environment:
```
Environment:
  Redmine version                4.1.0.stable
  Ruby version                   2.6.3-p62 (2019-04-16) [x86_64-linux]
  Rails version                  5.2.4.1
  Environment                    production
  Database adapter               PostgreSQL
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Subversion                     1.7.14
  Mercurial                      5.2.2
  Bazaar                         2.5.1
  Git                            2.9.3
  Filesystem                     
  Xitolite                       2.9.3
Redmine plugins:
  additionals                    2.0.23
  progressive_projects_list      4.0.0
  redmine_git_hosting            4.0.1
  redmine_issue_badge            0.1.3
  redmine_tags                   4.0.0
```

**Comment by chrislockwood** [comment]
I have the same issue, perhaps a conflict with another plugin?

```
Completed 500 Internal Server Error in 255ms (ActiveRecord: 110.9ms)
  
ActionView::Template::Error (super: no superclass method `column_content' for #<#<Class:0x000000000c57ecc8>:0x0000000010085bf0>
Did you mean?  column_content_without_tags):
    33:   <% end %>
    34:   <tr id="issue-<%= issue.id %>" class="hascontextmenu <%= cycle('odd', 'even') %> <%= issue.css_classes %> <%= level > 0 ? "idnt idnt-#{level}" : nil %>">
    35:     <td class="checkbox hide-when-print"><%= check_box_tag("ids[]", issue.id, false, :id => nil) %></td>
    36:     <% query.inline_columns.each do |column| %>
    37:     <%= content_tag('td', column_content(column, issue), :class => column.css_classes) %>
    38:     <% end %>
    39:     <td class="buttons"><%= link_to_context_menu %></td>
  
plugins/redmine_multiprojects_issue/lib/redmine_multiprojects_issue/queries_helper_patch.rb:18:in `column_content'
plugins/additional_tags/lib/additional_tags/patches/queries_helper_patch.rb:35:in `column_content_with_tags'
plugins/redmine_multiprojects_issue/lib/redmine_multiprojects_issue/queries_helper_patch.rb:18:in `column_content'
```

This plugin would be very helpful for my Redmine instance, it would be nice to think there was a workaround.

```
Environment:
  Redmine version                4.1.1.stable
  Ruby version                   2.6.6-p146 (2020-03-31) [x64-mingw32]
  Rails version                  5.2.4.2
  Environment                    production
  Database adapter               SQLServer
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Git                            2.29.2
  Filesystem                     
Redmine plugins:
  additional_tags                1.0.0
  additionals                    3.0.2-master
  redmine_banner                 0.3.4
  redmine_base_deface            1.5.3
  redmine_base_stimulusjs        1.1.1
  redmine_custom_auto_complete   0.0.1
  redmine_embed_html5_video      0.0.3
  redmine_impersonate            2.0.0
  redmine_mentions               0.0.1
  redmine_multiprojects_issue    4.1.0
  redmine_silencer               0.4.3
  redmine_smile_project_enumerations_custom_field_format 1.3.14
  redmine_sudo                   1.0.0
  redmine_theme_changer          0.4.0
  redmine_workflow_hidden_fields 0.5.0
```

**Comment by chrislockwood** [comment]
Sure enough `additional_tags` is the plugin we have clashed with.
