### ISSUE TITLE
500 Internal Error when accessing user profile view [Redmine 4.2.2]

### ISSUE THREAD

**Issue by chrislockwood** [nanego/redmine_multiprojects_issue#52]
When accessing user user profiles the following exception is thrown.  

```
Started GET "/users/5" for 10.144.32.236 at 2021-09-14 20:02:34 +0100
Processing by UsersController#show as HTML
  Parameters: {"id"=>"5"}
  Current user: chris_lockwood (id=5)
Completed 500 Internal Server Error in 544ms (ActiveRecord: 386.4ms)
  
NoMethodError (undefined method `where' for #<Proc:0x000000000cb27828>
Did you mean?  when):
  
plugins/redmine_multiprojects_issue/lib/redmine_multiprojects_issue/acts_as_activity_provider.rb:32:in `find_events'
lib/redmine/activity/fetcher.rb:93:in `block (2 levels) in events'
lib/redmine/activity/fetcher.rb:92:in `each'
lib/redmine/activity/fetcher.rb:92:in `block in events'
lib/redmine/activity/fetcher.rb:91:in `each'
lib/redmine/activity/fetcher.rb:91:in `events'
plugins/redmine_multiprojects_issue/lib/redmine_multiprojects_issue/activity_fetcher_patch.rb:6:in `events'
app/controllers/users_controller.rb:95:in `block (2 levels) in show'
app/controllers/users_controller.rb:93:in `show'
lib/redmine/sudo_mode.rb:61:in `sudo_mode'
```

**Comment by nanego** [comment]
That's weird. User profile is working well in our environments.
Do you have any other plugins installed?
Are the plugins all up to date?
