### ISSUE TITLE
Issues with plugin a_common_libs

### ISSUE THREAD

**Issue by dronmaxman** [nanego/redmine_multiprojects_issue#53]
My config
```
Debian 9.13
mariadb 10.1.48-0+deb9u2

Environment:
  Redmine version                3.4.11.stable
  Ruby version                   2.4.4-p296 (2018-03-28) [x86_64-linux]
  Rails version                  4.2.11.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Git                            2.11.0
  Filesystem                     
Redmine plugins:
  a_common_libs                  2.5.3
  clipboard_image_paste          1.13
  custom_menu                    1.8.6
  easy_gantt                     1.10
  progressive_projects_list      4.0.0
  projects_show                  0.0.3
  redmine_activity_report        1.2.10
  redmine_banner                 0.1.2
  redmine_base_deface            1.5.3
  redmine_base_stimulusjs        1.1.1
  redmine_changeauthor           1.0.1
  redmine_checklists             3.1.19
  redmine_email_images           0.1.1
  redmine_issue_dynamic_edit     0.7.2
  redmine_issue_evm              4.0
  redmine_issue_tabs             1.3.2
  redmine_login_audit            0.3.3
  redmine_logs                   0.2.0
  redmine_move_comments          0.0.2
  redmine_multiprojects_issue    3.4.5
  redmine_people                 1.6.1
  redmine_per_project_formatting 0.0.5
  redmine_pivot_table            0.0.7
  redmine_pretend                2.0.1
  redmine_reminder               0.3.0
  redmine_send_mails             0.3.23xBeta
  redmine_spent_time_required    0.0.1
  redmine_summed_fields          1.0.1
  redmine_update_reminder        1.1
  redmine_work_time              0.3.4
  redmine_workload               1.1.0
  sidebar_hide                   0.0.8
  subtask_columns                0.0.3
  that_email_log                 0.0.4
  timelog_timer                  2.0.0
  unread_issues                  2.2.3
```

I have a conflict between plugins a_common_libs and redmine_multiprojects when I try to open project like http://redmine.my.domain/projects/deps

```
Started GET "/projects" for 10.90.20.2 at 2021-10-07 23:57:53 +0300
Processing by ProjectsController#index as HTML
  Current user: admin (id=1)
  Rendered projects/index.html.erb within layouts/base (2557.9ms)
  Rendered inline template (0.4ms)
  Rendered plugins/redmine_pretend/app/views/user/_unpretend.html.erb (0.1ms)
  Rendered plugins/a_common_libs/app/views/hooks/a_common_libs/_html_head.html.erb (1.7ms)
  Rendered plugins/clipboard_image_paste/app/views/clipboard_image_paste/_headers.html.erb (0.4ms)
  Rendered plugins/custom_menu/app/views/hooks/custom_menu/_html_head.html.erb (0.7ms)
  Rendered plugins/progressive_projects_list/app/views/projects/_progressive_sidebar.html.erb (1.6ms)
  Rendered plugins/progressive_projects_list/app/views/application/_progressive_recent_projects.html.erb (0.1ms)
  Rendered plugins/redmine_banner/app/views/banner/_project_body_bottom.html.erb (0.1ms)
  Rendered plugins/sidebar_hide/app/views/sidebar/_hideButton_partial.html.erb (0.1ms)
  Rendered plugins/clipboard_image_paste/app/views/clipboard_image_paste/_add_form.html.erb (2.3ms)
  Rendered plugins/custom_menu/app/views/hooks/custom_menu/_view_layouts_base_body_bottom.erb (0.1ms)
  Rendered plugins/redmine_people/app/views/common/_people_select2_data.html.erb (0.2ms)
  Rendered plugins/redmine_people/app/views/common/_layout_bottom.html.erb (0.5ms)
Completed 200 OK in 2626ms (Views: 2402.9ms | ActiveRecord: 205.0ms)
Started GET "/projects/deps" for 10.90.20.2 at 2021-10-07 23:57:58 +0300
Processing by ProjectsController#show as HTML
  Parameters: {"id"=>"deps"}
  Current user: admin (id=1)
Completed 500 Internal Server Error in 68ms (ActiveRecord: 7.1ms)

SystemStackError (stack level too deep):
  plugins/redmine_multiprojects_issue/lib/redmine_multiprojects_issue/issue_patch.rb:22:in `visible_condition'
  plugins/a_common_libs/lib/acl/patches/models/issue_patch.rb:171:in `visible_condition_with_acl'
  plugins/redmine_multiprojects_issue/lib/redmine_multiprojects_issue/issue_patch.rb:32:in `visible_condition'
  plugins/a_common_libs/lib/acl/patches/models/issue_patch.rb:171:in `visible_condition_with_acl'
  plugins/redmine_multiprojects_issue/lib/redmine_multiprojects_issue/issue_patch.rb:32:in `visible_condition'
  plugins/a_common_libs/lib/acl/patches/models/issue_patch.rb:171:in `visible_condition_with_acl'
  plugins/redmine_multiprojects_issue/lib/redmine_multiprojects_issue/issue_patch.rb:32:in `visible_condition'
```

**Comment by nanego** [comment]
Working with Redmine 3 and other plugins, you can try this older version:
https://github.com/nanego/redmine_multiprojects_issue/releases/tag/v3.3.0
