### ISSUE TITLE
compatibility issue: does not work with redmine_dashboard 2 plugin

### ISSUE THREAD

**Issue by Raw1mage** [nanego/redmine_multiprojects_issue#69]
I, [2023-08-18T16:36:11.509243 #1]  INFO -- : Started GET "/projects/ilrdfmis/rdb/taskboard?&_=1692376570918" for 1.34.74.47 at 2023-08-18 16:36:11 +0000
I, [2023-08-18T16:36:11.510586 #1]  INFO -- : Processing by RdbTaskboardController#index as JS
I, [2023-08-18T16:36:11.510648 #1]  INFO -- :   Parameters: {"_"=>"1692376570918", "id"=>"ilrdfmis"}
I, [2023-08-18T16:36:11.516659 #1]  INFO -- :   Current user: sysadmin (id=1)
I, [2023-08-18T16:36:11.544754 #1]  INFO -- :   Rendered plugins/redmine_dashboard/app/views/rdb_dashboard/index.js.erb (Duration: 6.2ms | Allocations: 1534)
I, [2023-08-18T16:36:11.545006 #1]  INFO -- : Completed 500 Internal Server Error in 34ms (ActiveRecord: 7.6ms | Allocations: 8417)
F, [2023-08-18T16:36:11.546818 #1] FATAL -- :
ActionView::Template::Error (Couldn't find Tracker with 'id'=6 [WHERE `trackers`.`id` IN (SELECT DISTINCT `trackers`.`id` FROM `trackers` INNER JOIN `projects_trackers` ON `projects_trackers`.`tracker_id` = `trackers`.`id` INNER JOIN `projects` ON `projects`.`id` = `projects_trackers`.`project_id` WHERE `projects`.`id` IN (?, ?, ?, ?, ?))]):
    18:     - render_rdb_menu_list [:all] do |val|
    19:       = link_to t("rdb_filter_tracker_#{val}"), rdb_filter_path(tracker: val)
    20:     - render_rdb_menu_list @board.trackers do |val|

plugins/redmine_dashboard/app/models/rdb_tracker_filter.rb:50:in `title'
plugins/redmine_dashboard/app/views/rdb_dashboard/taskboard/_header.html.slim:17
plugins/redmine_dashboard/app/views/rdb_dashboard/_taskboard.html.slim:3
plugins/redmine_dashboard/app/views/rdb_dashboard/index.js.erb:1
lib/redmine/sudo_mode.rb:61:in `sudo_mode'

**Comment by Raw1mage** [comment]
This happens only in admin account, and cannot be undone by removing the multiproject_issue plugin.
Need advices in how to restore the changes made to the DB while installing the multiproject_issue plugin.
